site_name: Project Documentation
site_url: https://<username>.github.io/<repo>/
docs_dir: exported         
site_dir: site
use_directory_urls: true

theme:
  name: material
  features:
    - navigation.sections
    - navigation.tabs
    - content.code.copy
    - content.code.annotate

plugins:
  - search

markdown_extensions:
  - admonition
  - footnotes
  - tables
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.tabbed
  - attr_list

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Architecture: architecture.md
  - API Reference: api-reference.md
  - Configuration: configuration.md
  - Performance: performance.md
  - Deployment: deployment.md
  - Troubleshooting: troubleshooting.md
